package com.kt.donors.enums;

public enum Rank {
    ZASLUZONY_HONOROWY_DAWCA_KRWI_I_STOPNIA,
    ZASLUZONY_HONOROWY_DAWCA_KRWI_II_STOPNIA,
    ZASLUZONY_HONOROWY_DAWCA_KRWI_III_STOPNIA,
    HONOROWY_DAWCA_KRWI_ZASLUZONY_DLA_ZDROWIA_NARODU,
    ODZNAKA_HONOROWA_PCK_IV_STOPNIA,
    ODZNAKA_HONOROWA_PCK_III_STOPNIA,
    ODZNAKA_HONOROWA_PCK_II_STOPNIA,
    ODZNAKA_HONOROWA_PCK_I_STOPNIA,
    KRYSZTALOWE_SERCE,
    ZA_ZASLUGI_DLA_OCHRONY_ZDROWIA
}
